baseURL = "https://example.com"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Alan Purring"
theme = "papercss-hugo-theme"
googleAnalytics = "UA-123456789-1"
disqusShortname = "yourdiscussshortname"

[privacy]
  [privacy.disqus]
    disable = true

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

[imaging]
  quality = 99

[params]
  homeMetaContent = "A blog.. to say things."
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat = "Jan 2, 2006"
  navTitleLink = "/"

[menu]
  [[menu.nav]]
    name = "Blog"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Posts"
    url = "/post/"
    weight = 2
  [[menu.nav]]
    name = "About"
    url = "/about/"
    weight = 3

