[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.79.1"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "https://suspicious-hamilton-97e348.netlify.app/"

[[headers]]
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"
